# Generated by Django 3.2.7 on 2021-10-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, help_text={'unique': 'A user with this email already exists'}, max_length=254, unique=True),
        ),
    ]
